name: Frequent API ping with retry and login

on:
  schedule:
    - cron: '17 * * * *'
  workflow_dispatch:
    inputs:
      check_description:
        description: 'Descrição opcional para execução manual'
        required: false
        default: ''

jobs:
  ping-api:
    runs-on: ubuntu-latest

    steps:
      - name: Send POST with JSON body and handle errors
        id: ping
        run: |
          MAX_RETRIES=4   # 4 retries + 1 tentativa inicial = 5 no total
          RETRY_DELAY=120  # segundos (2 min)
          ATTEMPT=0

          EMAIL="teste@teste.com"
          PASSWORD="senha_secreta"
          
          while [ $ATTEMPT -le $MAX_RETRIES ]; do
            HTTP_STATUS=$(curl -X POST \
              -H "Content-Type: application/json" \
              -d "{\"email\":\"$EMAIL\",\"password\":\"$PASSWORD\"}" \
              -o /dev/null -s -w "%{http_code}" \
              https://inreader-api.onrender.com/auth/login)

            echo "Attempt $((ATTEMPT+1)): HTTP status code = $HTTP_STATUS"
            
            if [[ "$HTTP_STATUS" == "200" ]]; then
              echo "✅ Login OK!"
              exit 0
            elif [[ "$HTTP_STATUS" == "401" ]]; then
              echo "⚠️ Unauthorized, reached DB."
              exit 0
            else
              echo "❌ API returned error $HTTP_STATUS"
              if [ $ATTEMPT -lt $MAX_RETRIES ]; then
                echo "⏳ Retrying in $RETRY_DELAY seconds..."
                sleep $RETRY_DELAY
              else
                echo "🚨 Max attempts reached, stopping workflow."
                exit 1
              fi
            fi

            ATTEMPT=$((ATTEMPT+1))
          done
